apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: market-template-sandbox
  namespace: default
spec:
  secretName: market-template-sandbox
  issuerRef:
    name: market-template-sandbox-issuer
    kind: ClusterIssuer
  commonName: sandbox.protonmarket.com
  dnsNames:
  - sandbox.protonmarket.com
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: market-template-sandbox-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cindy@metalpay.co
    privateKeySecretRef:
      name:  market-template-sandbox
    solvers:
      - selector: {}
        http01:
          ingress:
            class: nginx
